apiVersion: apps/v1
kind: Deployment
metadata:
    name: runner-pod-npu-scheduler
    namespace: kube-system
    labels:
        component: runner-pod-npu-scheduler
spec:
    replicas: 1
    selector:
        matchLabels:
            component: runner-pod-npu-scheduler
    template:
        metadata:
            labels:
                component: runner-pod-npu-scheduler
        spec:
            serviceAccountName: runner-pod-npu-scheduler
            containers:
                - name: scheduler
                  image: docker.1ms.run/dodok0a/runner-pod-npu-scheduler:v1
                  command:
                      - ./runner-pod-npu-scheduler
                      - --config=/etc/kubernetes/scheduler-config.yaml
                      - --v=5
                  volumeMounts:
                      - name: config
                        mountPath: /etc/kubernetes
            volumes:
                - name: config
                  configMap:
                      name: runner-pod-npu-scheduler-config
